import argparse
import os.path
import sys
from .parser import SedgeConfig


def ask_overwrite(fname):
    print(
        "WARNING: `%s' already exists and was not generated by sedge." % fname,
        file=sys.stderr)
    confirm = input("Enter `yes' to overwite: ")
    return confirm == 'yes'


def check_or_confirm_overwrite(fname):
    "returns True if OK to proceed, False otherwise"
    try:
        with open(fname) as fd:
            header = next(fd)
            if header.find('generated by sedge') == -1:
                return ask_overwrite(fname)
    except OSError:
        pass
    except StopIteration:
        pass
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'config_file',
        default=os.path.expanduser('~/.sedge/config'),
        nargs='?')
    parser.add_argument(
        'output_file',
        default=os.path.expanduser('~/.ssh/config'),
        nargs='?')
    args = parser.parse_args()
    with open(args.config_file) as fd:
        config = SedgeConfig(fd)
    if args.output_file == '-':
        config.output(sys.stdout)
    else:
        if not check_or_confirm_overwrite(args.output_file):
            print("Aborting.", file=sys.stderr)
            sys.exit(1)
        with open(args.output_file, 'w') as fd:
            fd.write(
                '# this configuration generated by '
                'sedge from source file: %s\n\n' % (args.output_file))
            config.output(fd)
